GET http://localhost:5082/games

###
GET http://localhost:5082/games/3c4e0419-8bda-49ea-b23d-369f6a14db18

###
POST http://localhost:5082/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genreId": "02f49762-0a06-414d-8f5a-f8d8886d3f3e",
    "price": 19.99,
    "releaseDate": "2011-11-18",
    "description": "Minecraft is a sandbox game where players build, explore, and survive in a blocky, procedurally generated world."
}

###
PUT http://localhost:5082/games/530f9f62-6c7c-4972-8b16-3be5ee6860c1
Content-Type: application/json 

{
    "name": "",
    "genre": "Fighting",
    "price": 9.99,
    "releaseDate": "1992-07-15"
}

###
DELETE  http://localhost:5082/games/5191a7ff-d81b-4a47-b12e-501be17378b9

###
GET http://localhost:5082/genres